<<<<<<< Updated upstream
webtalk_init -webtalk_dir C:\\Users\\wojte\\Desktop\\pul_fpga_projekt_qr\\QR_Reader\\sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-01-06 19:31:18" -context "software_version_and_target_device"
=======
webtalk_init -webtalk_dir C:\\Users\\wojte\\Desktop\\Nowy_folder\\QR_Reader\\sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-01-06 02:33:19" -context "software_version_and_target_device"
>>>>>>> Stashed changes
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
<<<<<<< Updated upstream
webtalk_add_data -client project -key random_id -value "ribjmm6190gjg1oj1rdipc1ask" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_43" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "43" -context "software_version_and_target_device"
=======
webtalk_add_data -client project -key random_id -value "secvp3ah7advo4plbhj6nfb37c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_42" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "42" -context "software_version_and_target_device"
>>>>>>> Stashed changes
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.175 GB" -context "user_environment"
webtalk_register_client -client sdk
<<<<<<< Updated upstream
webtalk_add_data -client sdk -key uid -value "1578327452813" -context "sdk\\\\hardware/1578327452813"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1578327452813"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1578327452813"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1578327452813"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1578327452813"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1578327452813"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1578327452813"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1578327452813"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1578327452813"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1578327452813"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1578327452813"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1578335478900"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1578335478900"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1578335478900"
webtalk_add_data -client sdk -key DebugCount -value "129" -context "sdk\\\\bsp/1578335478900"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1578335478900"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1578335478900"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1578335478900"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1578335478900"
webtalk_transmit -clientid 1580964562 -regid "" -xml C:\\Users\\wojte\\Desktop\\pul_fpga_projekt_qr\\QR_Reader\\sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\wojte\\Desktop\\pul_fpga_projekt_qr\\QR_Reader\\sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\wojte\\Desktop\\pul_fpga_projekt_qr\\QR_Reader\\sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
=======
webtalk_add_data -client sdk -key uid -value "1578273787813" -context "sdk\\\\hardware/1578273787813"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1578273787813"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1578273787813"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1578273787813"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1578273787813"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1578273787813"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1578273787813"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1578273787813"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1578273787813"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1578273787813"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1578273787813"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1578274399015"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1578274399015"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1578274399015"
webtalk_add_data -client sdk -key DebugCount -value "5" -context "sdk\\\\bsp/1578274399015"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1578274399015"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1578274399015"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1578274399015"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1578274399015"
webtalk_transmit -clientid 2747182333 -regid "" -xml C:\\Users\\wojte\\Desktop\\Nowy_folder\\QR_Reader\\sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\wojte\\Desktop\\Nowy_folder\\QR_Reader\\sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\wojte\\Desktop\\Nowy_folder\\QR_Reader\\sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
>>>>>>> Stashed changes
webtalk_terminate
